---
- name: Install and Configure MicroK8s
  hosts: gitops2
  become: yes
  vars:
    hostname: gitops2
    timezone: Asia/Seoul
    ip_address: 10.0.2.31/24
    gateway: 10.0.2.1
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    user: ubuntu

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    - name: Disable swap
      command: swapoff -a     # 가상 메모리 비활성화
      changed_when: false

    - name: Remove swap from fstab
      replace:                # 재부팅시에도 가상 메모리 비활성화
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Synchronize hardware clock
      command: hwclock      # 로컬 시간을 시스템에 반영
      changed_when: false

    - name: Disable UFW
      ufw:                  # UFW 모듈을 이용해서 방화벽 비활성화
        state: disabled

    #    - name: Configure network
    #      template:        # template 모듈을 이용해서 네트워크 설정 구성
    #                       # 즉, jinja2 템플릿 형식을 이용해서 동적으로 설정파일 생성
    #        src: 07netplan.j2    # 원본 템플릿 지정
    #        dest: /etc/netplan/00-installer-config.yaml    # 템플릿의 내용을 복사할 파일 지정
    #      notify: Apply netplan    # 작업 완료후 추가 작업을 위한 핸들러 호출

    - name: Install MicroK8s
      snap:                     # snap 모듈을 이용해서 microk8s 설치
        name: microk8s
        classic: yes

    # sudo usermod -a -G microk8s ubunt
    - name: Add user to microk8s group
      user:                     # user 모듈을 이용해서 ubuntu 계정을 microk8s 그룹에 추가
        name: "{{ user }}"
        groups: microk8s
        append: yes

    - name: Create .kube directory
      file:                     # file 모듈을 이용해서 디렉토리 생성
        path: "/home/{{ user }}/.kube"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    # sudo chown -R ubuntu ~/.kube
    - name: Change ownership of .kube directory
      file:                     # file 모듈을 이용해서 소유자 변경
        path: "/home/{{ user }}/.kube"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes            # 하위 디렉토리들도 동일한 소유자로 변경

    - name: Add PATH to .bashrc
      lineinfile:               # lineinfile 모듈을 이용해서 두 문장을 PATH로 설정
        path: "/home/{{ user }}/.bashrc"
        line: "{{ item }}"
      loop:
        - 'export PATH=$PATH:/usr/snap/bin'
        - 'export PATH=$PATH:/snap/bin'

    - name: Add alias for microk8s kubectl
      lineinfile:               # microk8s kubectl에 대한 별칠 설정
        path: "/home/{{ user }}/.bashrc"
        line: "alias mk='microk8s kubectl'"

    - name: Get MicroK8s kubeconfig and save to ~/.kube/config
      command: microk8s config    # 쿠버네티스 설정 가져오기
      register: kubeconfig_output

    - name: Write kubeconfig to file
      copy:                       # 쿠버네티스 설정을 .kube/config에 저장
        content: "{{ kubeconfig_output.stdout }}"
        dest: /home/{{ user }}/.kube/config
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0600'  # 파일 권한 설정